services:
  - type: web
    name: azadi-website
    env: node
    plan: free
    buildCommand: npm install --production=false && node build-render.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
