services:
  - type: web
    name: azadi-website
    env: node
    plan: free
    root: ./
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
